namespace HashSlinger.Api.Models;

using System.ComponentModel.DataAnnotations.Schema;

/// <summary>A mapping table of users to their access groups.</summary>
/// <autogeneratedoc />
public class AccessGroupUser
{
    /// <summary>Gets or sets the identifier.</summary>
    /// <value>The identifier.</value>
    /// <autogeneratedoc />
    public int Id { get; set; }

    /// <summary>Gets or sets the access group identifier.</summary>
    /// <value>The access group identifier.</value>
    /// <autogeneratedoc />
    public int AccessGroupId { get; set; }

    /// <summary>Gets or sets the user identifier.</summary>
    /// <value>The user identifier.</value>
    /// <autogeneratedoc />
    public int UserId { get; set; }

    /// <summary>Gets or sets the access group.</summary>
    /// <value>The access group.</value>
    /// <autogeneratedoc />
    [ForeignKey("AccessGroupId")]
    [InverseProperty("AccessGroupUsers")]
    public virtual AccessGroup AccessGroup { get; set; } = null!;

    /// <summary>Gets or sets the user.</summary>
    /// <value>The user.</value>
    /// <autogeneratedoc />
    [ForeignKey("UserId")]
    [InverseProperty("AccessGroupUsers")]
    public virtual User User { get; set; } = null!;
}
