namespace HashSlinger.Api.Models;

using System.ComponentModel.DataAnnotations;

/// <summary>Represents an Access Group, typically associated with a project or operation.</summary>
public record AccessGroup
{
    /// <summary>Gets or sets the access group agents.</summary>
    /// <value>The access group agents.</value>
    public virtual ICollection<Agent> Agents { get; set; } = new List<Agent>();

    /// <summary>Gets or sets the files.</summary>
    /// <value>The files.</value>
    public virtual ICollection<File> Files { get; set; } = new List<File>();

    /// <summary>Gets or sets the hashlists.</summary>
    /// <value>The hashlists.</value>
    /// <autogeneratedoc />
    public virtual ICollection<Hashlist> Hashlists { get; set; } = new List<Hashlist>();

    public virtual ICollection<RegistrationVoucher> RegistrationVouchers { get; set; }
        = new List<RegistrationVoucher>();

    /// <summary>Gets or sets the task wrappers.</summary>
    /// <value>The task wrappers.</value>
    /// <autogeneratedoc />
    public virtual ICollection<TaskWrapper> TaskWrappers { get; set; } = new List<TaskWrapper>();

    /// <summary>Gets or sets the access group users.</summary>
    /// <value>The access group users.</value>
    public virtual ICollection<User> Users { get; set; } = new List<User>();

    /// <summary>Gets or sets the identifier.</summary>
    /// <value>The identifier.</value>
    public int Id { get; set; }

    /// <summary>Gets or sets the name of the group.</summary>
    /// <value>The name of the group.</value>
    [StringLength(50)]
    public string Name { get; set; } = null!;
}
