namespace HashSlingerApi.Models;

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

/// <summary>Represents an Access Group, typically associated with a project or operation.</summary>
public class AccessGroup
{
    /// <summary>Gets or sets the identifier.</summary>
    /// <value>The identifier.</value>
    public int Id { get; set; }

    /// <summary>Gets or sets the name of the group.</summary>
    /// <value>The name of the group.</value>
    [StringLength(50)]
    public string GroupName { get; set; } = null!;

    /// <summary>Gets or sets the access group agents.</summary>
    /// <value>The access group agents.</value>
    [InverseProperty("AccessGroup")]
    public virtual ICollection<AccessGroupAgent> AccessGroupAgents { get; set; } = new List<AccessGroupAgent>();

    /// <summary>Gets or sets the access group users.</summary>
    /// <value>The access group users.</value>
    [InverseProperty("AccessGroup")]
    public virtual ICollection<AccessGroupUser> AccessGroupUsers { get; set; } = new List<AccessGroupUser>();

    /// <summary>Gets or sets the files.</summary>
    /// <value>The files.</value>
    [InverseProperty("AccessGroup")]
    public virtual ICollection<File> Files { get; set; } = new List<File>();

    /// <summary>Gets or sets the hashlists.</summary>
    /// <value>The hashlists.</value>
    /// <autogeneratedoc />
    [InverseProperty("AccessGroup")]
    public virtual ICollection<Hashlist> Hashlists { get; set; } = new List<Hashlist>();

    /// <summary>Gets or sets the task wrappers.</summary>
    /// <value>The task wrappers.</value>
    /// <autogeneratedoc />
    [InverseProperty("AccessGroup")]
    public virtual ICollection<TaskWrapper> TaskWrappers { get; set; } = new List<TaskWrapper>();
}
