namespace HashSlinger.Api.Models;

using System.ComponentModel.DataAnnotations.Schema;

/// <summary>A mapping table of zaps to agents.</summary>
/// <autogeneratedoc />
public record AgentZap
{
    /// <summary>Gets or sets the identifier.</summary>
    /// <value>The identifier.</value>
    /// <autogeneratedoc />
    public int Id { get; set; }

    /// <summary>Gets or sets the agent identifier.</summary>
    /// <value>The agent identifier.</value>
    /// <autogeneratedoc />
    public int AgentId { get; set; }

    /// <summary>Gets or sets the last zap identifier.</summary>
    /// <value>The last zap identifier.</value>
    /// <autogeneratedoc />
    public int? LastZapId { get; set; }

    /// <summary>Gets or sets the agent.</summary>
    /// <value>The agent.</value>
    /// <autogeneratedoc />
    public virtual Agent Agent { get; set; } = null!;

    /// <summary>Gets or sets the last zap.</summary>
    /// <value>The last zap.</value>
    /// <autogeneratedoc />
    public virtual Zap? LastZap { get; set; }
}
