namespace HashSlinger.Api.Models;

using System.ComponentModel.DataAnnotations;

/// <summary>A copy of the hashtopolis agent software.</summary>
/// <autogeneratedoc />
public record AgentBinary : DownloadableBinary
{
    /// <inheritdoc />
    public AgentBinary() => Name = "agent";

    /// <summary>Gets or sets the type.</summary>
    /// <value>The type.</value>
    /// <autogeneratedoc />
    [StringLength(20)]
    [Required]
    public string Type { get; set; } = null!;

    /// <summary>Gets or sets the update available.</summary>
    /// <value>The update available.</value>
    /// <autogeneratedoc />
    [StringLength(20)]
    public string UpdateAvailable { get; set; } = null!;

    /// <summary>Gets or sets the update track.</summary>
    /// <value>The update track (stable, beta, dev, etc.).</value>
    [Required]
    [StringLength(20)]
    public string UpdateTrack { get; set; } = "stable";
}
