namespace HashSlinger.Api.Models;

using System.ComponentModel.DataAnnotations;

/// <summary>A copy of the hashtopolis agent software.</summary>
/// <autogeneratedoc />
public record AgentBinary
{
    /// <summary>Gets or sets the identifier.</summary>
    /// <value>The identifier.</value>
    /// <autogeneratedoc />
    public int Id { get; set; }

    /// <summary>Gets or sets the type.</summary>
    /// <value>The type.</value>
    /// <autogeneratedoc />
    [StringLength(20), Required]
    public string Type { get; set; } = null!;

    /// <summary>Gets or sets the version.</summary>
    /// <value>The version.</value>
    /// <autogeneratedoc />
    [StringLength(20), Required]
    public string Version { get; set; } = null!;

    /// <summary>Gets or sets the operating systems.</summary>
    /// <value>The operating systems.</value>
    /// <autogeneratedoc />
    [StringLength(50), Required]
    public string OperatingSystems { get; set; } = null!;

    /// <summary>Gets or sets the name of the file.</summary>
    /// <value>The name of the file.</value>
    [StringLength(50), Required]
    public string FileName { get; set; } = null!;

    /// <summary>Gets or sets the update track.</summary>
    /// <value>The update track (stable, beta, dev, etc.).</value>
    [Required, StringLength(20)]
    public string UpdateTrack { get; set; } = "stable";

    /// <summary>Gets or sets the download URL.</summary>
    /// <value>The download URL.</value>
    [Required]
    public string DownloadUrl { get; set; } = null!;

    /// <summary>Gets or sets the update available.</summary>
    /// <value>The update available.</value>
    /// <autogeneratedoc />
    [StringLength(20)]
    public string UpdateAvailable { get; set; } = null!;
}
