namespace HashSlinger.Api.Models;

using System.ComponentModel.DataAnnotations;

/// <summary>A group of API accesses</summary>
/// <autogeneratedoc />
public record ApiGroup
{
    /// <summary>Gets or sets the identifier.</summary>
    /// <value>The identifier.</value>
    /// <autogeneratedoc />
    public int Id { get; set; }

    /// <summary>Gets or sets the name.</summary>
    /// <value>The name.</value>
    /// <autogeneratedoc />
    [StringLength(100)]
    public string Name { get; set; } = null!;

    /// <summary>Gets or sets the permissions.</summary>
    /// <value>The permissions.</value>
    /// <autogeneratedoc />
    public string Permissions { get; set; } = null!;

    /// <summary>Gets or sets the API keys.</summary>
    /// <value>The API keys.</value>
    /// <autogeneratedoc />
    public virtual ICollection<ApiKey> ApiKeys { get; set; } = new List<ApiKey>();
}
