namespace HashSlinger.Api.Models;

using System.ComponentModel.DataAnnotations.Schema;

/// <summary>The assignment of a task to an agent.</summary>
/// <autogeneratedoc />
public class Assignment
{
    /// <summary>Gets or sets the identifier.</summary>
    /// <value>The identifier.</value>
    /// <autogeneratedoc />
    public int Id { get; set; }

    /// <summary>Gets or sets the task identifier.</summary>
    /// <value>The task identifier.</value>
    /// <autogeneratedoc />
    public int TaskId { get; set; }

    /// <summary>Gets or sets the agent identifier.</summary>
    /// <value>The agent identifier.</value>
    /// <autogeneratedoc />
    public int AgentId { get; set; }

    /// <summary>Gets or sets the benchmark.</summary>
    /// <value>The benchmark.</value>
    /// <autogeneratedoc />
    public string Benchmark { get; set; } = null!;

    /// <summary>Gets or sets the agent.</summary>
    /// <value>The agent.</value>
    /// <autogeneratedoc />
    [ForeignKey("AgentId")]
    [InverseProperty("Assignments")]
    public virtual Agent Agent { get; set; } = null!;

    /// <summary>Gets or sets the task.</summary>
    /// <value>The task.</value>
    /// <autogeneratedoc />
    [ForeignKey("TaskId")]
    [InverseProperty("Assignments")]
    public virtual Task Task { get; set; } = null!;
}
