namespace HashSlinger.Api.Models;

using System.ComponentModel.DataAnnotations.Schema;

/// <summary>A chunk of a cracking task.</summary>
/// <autogeneratedoc />
public class Chunk
{
    /// <summary>Gets or sets the identifier.</summary>
    /// <value>The identifier.</value>
    /// <autogeneratedoc />
    public int Id { get; set; }

    /// <summary>Gets or sets the task identifier.</summary>
    /// <value>The task identifier.</value>
    /// <autogeneratedoc />
    public int TaskId { get; set; }

    /// <summary>Gets or sets the skip.</summary>
    /// <value>The skip.</value>
    /// <autogeneratedoc />
    [Column(TypeName = "decimal(20, 0)")]
    public decimal Skip { get; set; }

    /// <summary>Gets or sets the length.</summary>
    /// <value>The length.</value>
    /// <autogeneratedoc />
    [Column(TypeName = "decimal(20, 0)")]
    public decimal Length { get; set; }

    /// <summary>Gets or sets the agent identifier.</summary>
    /// <value>The agent identifier.</value>
    /// <autogeneratedoc />
    public int? AgentId { get; set; }

    /// <summary>Gets or sets the dispatch time.</summary>
    /// <value>The dispatch time.</value>
    /// <autogeneratedoc />
    public DateTime DispatchTime { get; set; }

    /// <summary>Gets or sets the solve time.</summary>
    /// <value>The solve time.</value>
    /// <autogeneratedoc />
    public DateTime SolveTime { get; set; }

    /// <summary>Gets or sets the checkpoint.</summary>
    /// <value>The checkpoint.</value>
    /// <autogeneratedoc />
    [Column(TypeName = "decimal(20, 0)")]
    public decimal Checkpoint { get; set; }

    /// <summary>Gets or sets the progress.</summary>
    /// <value>The progress.</value>
    /// <autogeneratedoc />
    public int? Progress { get; set; }

    /// <summary>Gets or sets the state.</summary>
    /// <value>The state.</value>
    /// <autogeneratedoc />
    public int State { get; set; }

    /// <summary>Gets or sets the cracked.</summary>
    /// <value>The cracked.</value>
    /// <autogeneratedoc />
    public int Cracked { get; set; }

    /// <summary>Gets or sets the speed.</summary>
    /// <value>The speed.</value>
    /// <autogeneratedoc />
    public long Speed { get; set; }

    /// <summary>Gets or sets the agent.</summary>
    /// <value>The agent.</value>
    /// <autogeneratedoc />
    [ForeignKey("AgentId")]
    [InverseProperty("Chunks")]
    public virtual Agent? Agent { get; set; }

    /// <summary>Gets or sets the hash binaries.</summary>
    /// <value>The hash binaries.</value>
    /// <autogeneratedoc />
    [InverseProperty("Chunk")]
    public virtual ICollection<HashBinary> HashBinaries { get; set; } = new List<HashBinary>();

    /// <summary>Gets or sets the hashes.</summary>
    /// <value>The hashes.</value>
    /// <autogeneratedoc />
    [InverseProperty("Chunk")]
    public virtual ICollection<Hash> Hashes { get; set; } = new List<Hash>();

    /// <summary>Gets or sets the task.</summary>
    /// <value>The task.</value>
    /// <autogeneratedoc />
    [ForeignKey("TaskId")]
    [InverseProperty("Chunks")]
    public virtual Task Task { get; set; } = null!;
}
