namespace HashSlinger.Api.Models;

using System.ComponentModel.DataAnnotations;

/// <summary>A binary that can be downloaded from the server.</summary>
public record DownloadableBinary
{
    /// <summary>Gets or sets the name of the binary.</summary>
    /// <value>The name of the binary.</value>
    /// <autogeneratedoc />
    [StringLength(256)]
    public string BinaryName { get; set; } = null!;

    /// <summary>Gets or sets the download URL.</summary>
    /// <value>The download URL.</value>
    /// <autogeneratedoc />
    [StringLength(150)]
    public string DownloadUrl { get; set; } = null!;

    /// <summary>Gets or sets the file.</summary>
    /// <value>The file.</value>
    public File? File { get; set; }

    /// <summary>Gets or sets the identifier.</summary>
    /// <value>The identifier.</value>
    /// <autogeneratedoc />
    public int Id { get; set; }

    /// <summary>Gets or sets the name.</summary>
    /// <value>The name.</value>
    /// <autogeneratedoc />
    [StringLength(256)]
    public string Name { get; set; } = null!;


    /// <summary>Gets or sets the operating systems.</summary>
    /// <value>The operating systems.</value>
    /// <autogeneratedoc />
    [Required]
    public List<string> OperatingSystems { get; set; } = new();

    /// <summary>Gets or sets the version.</summary>
    /// <value>The version.</value>
    /// <autogeneratedoc />
    [StringLength(20)]
    public string Version { get; set; } = null!;
}
