namespace HashSlingerApi.Models;

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

/// <summary>A mapping between a task and an associated file.</summary>
/// <autogeneratedoc />
public class FileTask
{
    /// <summary>Gets or sets the identifier.</summary>
    /// <value>The identifier.</value>
    /// <autogeneratedoc />
    public int Id { get; set; }

    /// <summary>Gets or sets the file identifier.</summary>
    /// <value>The file identifier.</value>
    /// <autogeneratedoc />
    public int FileId { get; set; }

    /// <summary>Gets or sets the task identifier.</summary>
    /// <value>The task identifier.</value>
    /// <autogeneratedoc />
    public int TaskId { get; set; }

    /// <summary>Gets or sets the file.</summary>
    /// <value>The file.</value>
    /// <autogeneratedoc />
    [ForeignKey("FileId")]
    [InverseProperty("FileTasks")]
    public virtual File File { get; set; } = null!;

    /// <summary>Gets or sets the task.</summary>
    /// <value>The task.</value>
    /// <autogeneratedoc />
    [ForeignKey("TaskId")]
    [InverseProperty("FileTasks")]
    public virtual Task Task { get; set; } = null!;
}
