namespace HashSlinger.Api.Models;

using System.ComponentModel.DataAnnotations;

/// <summary>A file deletion event.</summary>
/// <autogeneratedoc />
public class FileDelete
{
    /// <summary>Gets or sets the identifier.</summary>
    /// <value>The identifier.</value>
    /// <autogeneratedoc />
    public int Id { get; set; }

    /// <summary>Gets or sets the filename.</summary>
    /// <value>The filename.</value>
    /// <autogeneratedoc />
    [StringLength(256)]
    public string Filename { get; set; } = null!;

    /// <summary>Gets or sets the time.</summary>
    /// <value>The time.</value>
    /// <autogeneratedoc />
    public DateTime Time { get; set; }
}
