namespace HashSlinger.Api.Models;

/// <summary>A mapping between a task and an associated file.</summary>
/// <autogeneratedoc />
public record FileTask
{
    /// <summary>Gets or sets the identifier.</summary>
    /// <value>The identifier.</value>
    /// <autogeneratedoc />
    public int Id { get; set; }

    /// <summary>Gets or sets the file identifier.</summary>
    /// <value>The file identifier.</value>
    /// <autogeneratedoc />
    public int FileId { get; set; }

    /// <summary>Gets or sets the task identifier.</summary>
    /// <value>The task identifier.</value>
    /// <autogeneratedoc />
    public int TaskId { get; set; }

    /// <summary>Gets or sets the file.</summary>
    /// <value>The file.</value>
    /// <autogeneratedoc />
    public virtual File File { get; set; } = null!;

    /// <summary>Gets or sets the task.</summary>
    /// <value>The task.</value>
    /// <autogeneratedoc />
    public virtual Task Task { get; set; } = null!;
}
