namespace HashSlinger.Api.Models;

using System.ComponentModel.DataAnnotations;

/// <summary>A distinct, selectable hashtype supported by hashcat.</summary>
/// <autogeneratedoc />
public record HashType
{
    /// <summary>Gets or sets the hashlists.</summary>
    /// <value>The hashlists.</value>
    /// <autogeneratedoc />
    public virtual ICollection<Hashlist> Hashlists { get; set; } = new List<Hashlist>();

    /// <summary>Gets or sets the description.</summary>
    /// <value>The description.</value>
    /// <autogeneratedoc />
    [StringLength(256)]
    public string Description { get; set; } = null!;

    /// <summary>Gets or sets the identifier.</summary>
    /// <value>The identifier.</value>
    /// <autogeneratedoc />
    public Guid Id { get; set; } = new();


    /// <summary>Gets or sets the hashcat identifier.</summary>
    /// <value>The hashcat identifier.</value>
    public int HashcatId { get; set; }


    /// <summary>Gets or sets a value indicating whether this instance is salted.</summary>
    /// <value><c>true</c> if this instance is salted; otherwise, <c>false</c>.</value>
    /// <autogeneratedoc />
    public bool IsSalted { get; set; }

    /// <summary>Gets or sets a value indicating whether this instance is slow hash.</summary>
    /// <value><c>true</c> if this instance is slow hash; otherwise, <c>false</c>.</value>
    /// <autogeneratedoc />
    public bool IsSlowHash { get; set; }

    /// <summary>Gets or sets the health checks.</summary>
    /// <value>The health checks.</value>
    public virtual ICollection<HealthCheck> HealthChecks { get; set; } = new List<HealthCheck>();
}
