namespace HashSlingerApi.Models;

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

/// <summary>A distinct, selectable hashtype supported by hashcat.</summary>
/// <autogeneratedoc />
public class HashType
{
    /// <summary>Gets or sets the identifier.</summary>
    /// <value>The identifier.</value>
    /// <autogeneratedoc />
    public int Id { get; set; }


    /// <summary>Gets or sets the description.</summary>
    /// <value>The description.</value>
    /// <autogeneratedoc />
    [StringLength(256)]
    public string Description { get; set; } = null!;

    /// <summary>Gets or sets a value indicating whether this instance is salted.</summary>
    /// <value>
    ///   <c>true</c> if this instance is salted; otherwise, <c>false</c>.</value>
    /// <autogeneratedoc />
    public bool IsSalted { get; set; }

    /// <summary>Gets or sets a value indicating whether this instance is slow hash.</summary>
    /// <value>
    ///   <c>true</c> if this instance is slow hash; otherwise, <c>false</c>.</value>
    /// <autogeneratedoc />
    public bool IsSlowHash { get; set; }

    /// <summary>Gets or sets the hashlists.</summary>
    /// <value>The hashlists.</value>
    /// <autogeneratedoc />
    [InverseProperty("HashType")]
    public virtual ICollection<Hashlist> Hashlists { get; set; } = new List<Hashlist>();
}
