namespace HashSlinger.Api.Models;

using System.ComponentModel.DataAnnotations;

/// <summary>Represents a binary hash. Typically used for WIFI hashes.</summary>
/// <autogeneratedoc />
public record HashBinary
{
    /// <summary>Gets or sets the chunk.</summary>
    /// <value>The chunk.</value>
    /// <autogeneratedoc />
    public virtual Chunk? Chunk { get; set; }

    /// <summary>Gets or sets the hashlist.</summary>
    /// <value>The hashlist.</value>
    /// <autogeneratedoc />
    public virtual Hashlist Hashlist { get; set; } = null!;

    /// <summary>Gets or sets the chunk identifier.</summary>
    /// <value>The chunk identifier.</value>
    /// <autogeneratedoc />
    public int? ChunkId { get; set; }

    /// <summary>Gets or sets the crack position.</summary>
    /// <value>The crack position.</value>
    /// <autogeneratedoc />
    public ulong CrackPos { get; set; }

    /// <summary>Gets or sets the essid.</summary>
    /// <value>The essid.</value>
    /// <autogeneratedoc />
    // ReSharper disable once IdentifierTypo
    public string Essid { get; set; } = null!;

    /// <summary>Gets or sets the hash.</summary>
    /// <value>The hash.</value>
    /// <autogeneratedoc />
    public string Hash { get; set; } = null!;

    /// <summary>Gets or sets the hashlist identifier.</summary>
    /// <value>The hashlist identifier.</value>
    /// <autogeneratedoc />
    public int HashlistId { get; set; }

    /// <summary>Gets or sets the identifier.</summary>
    /// <value>The identifier.</value>
    /// <autogeneratedoc />
    public int Id { get; set; }

    /// <summary>Gets or sets a value indicating whether this instance is cracked.</summary>
    /// <value><c>true</c> if this instance is cracked; otherwise, <c>false</c>.</value>
    /// <autogeneratedoc />
    public bool IsCracked { get; set; }

    /// <summary>Gets or sets the plaintext.</summary>
    /// <value>The plaintext.</value>
    /// <autogeneratedoc />
    [StringLength(1024)]
    public string? Plaintext { get; set; }

    /// <summary>Gets or sets the time cracked.</summary>
    /// <value>The time cracked.</value>
    /// <autogeneratedoc />
    public DateTime? TimeCracked { get; set; }
}
