namespace HashSlinger.Api.Models;

/// <summary>A mapping table between parent and child hashlists.</summary>
/// <autogeneratedoc />
public record HashlistHashlist
{
    /// <summary>Gets or sets the identifier.</summary>
    /// <value>The identifier.</value>
    /// <autogeneratedoc />
    public int Id { get; set; }

    /// <summary>Gets or sets the parent hashlist identifier.</summary>
    /// <value>The parent hashlist identifier.</value>
    /// <autogeneratedoc />
    public int ParentHashlistId { get; set; }

    /// <summary>Gets or sets the hashlist identifier.</summary>
    /// <value>The hashlist identifier.</value>
    /// <autogeneratedoc />
    public int HashlistId { get; set; }

    /// <summary>Gets or sets the hashlist.</summary>
    /// <value>The hashlist.</value>
    /// <autogeneratedoc />
    public virtual Hashlist Hashlist { get; set; } = null!;

    /// <summary>Gets or sets the parent hashlist.</summary>
    /// <value>The parent hashlist.</value>
    /// <autogeneratedoc />
    public virtual Hashlist ParentHashlist { get; set; } = null!;
}
