namespace HashSlinger.Api.Models;

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

/// <summary>Represents a health check task.</summary>
/// <autogeneratedoc />
public record HealthCheck
{
    /// <summary>Gets or sets the identifier.</summary>
    /// <value>The identifier.</value>
    /// <autogeneratedoc />
    public int Id { get; set; }

    /// <summary>Gets or sets the time.</summary>
    /// <value>The time.</value>
    /// <autogeneratedoc />
    public DateTime Time { get; set; }

    /// <summary>Gets or sets the status.</summary>
    /// <value>The status.</value>
    /// <autogeneratedoc />
    public int Status { get; set; }

    /// <summary>Gets or sets the type of the check.</summary>
    /// <value>The type of the check.</value>
    /// <autogeneratedoc />
    public int CheckType { get; set; }

    /// <summary>Gets or sets the hashtype identifier.</summary>
    /// <value>The hashtype identifier.</value>
    /// <autogeneratedoc />
    public int HashtypeId { get; set; }

    /// <summary>Gets or sets the cracker binary identifier.</summary>
    /// <value>The cracker binary identifier.</value>
    /// <autogeneratedoc />
    public int CrackerBinaryId { get; set; }

    /// <summary>Gets or sets the expected cracks.</summary>
    /// <value>The expected cracks.</value>
    /// <autogeneratedoc />
    public int ExpectedCracks { get; set; }

    /// <summary>Gets or sets the attack command.</summary>
    /// <value>The attack command.</value>
    /// <autogeneratedoc />
    [StringLength(256)]
    public string AttackCmd { get; set; } = null!;

    /// <summary>Gets or sets the cracker binary.</summary>
    /// <value>The cracker binary.</value>
    /// <autogeneratedoc />
    public virtual CrackerBinary CrackerBinary { get; set; } = null!;

    /// <summary>Gets or sets the health check agents.</summary>
    /// <value>The health check agents.</value>
    /// <autogeneratedoc />
    public virtual ICollection<HealthCheckAgent> HealthCheckAgents { get; set; }
        = new List<HealthCheckAgent>();
}
