namespace HashSlinger.Api.Models;

using System.ComponentModel.DataAnnotations;
using Enums;

/// <summary>Represents a health check task.</summary>
/// <autogeneratedoc />
public record HealthCheck
{
    /// <summary>Gets or sets the cracker binary.</summary>
    /// <value>The cracker binary.</value>
    /// <autogeneratedoc />
    public virtual CrackerBinary CrackerBinary { get; set; } = null!;

    /// <summary>Gets or sets the health check agents.</summary>
    /// <value>The health check agents.</value>
    /// <autogeneratedoc />
    public virtual ICollection<HealthCheckAgent> HealthCheckAgents { get; set; } = new List<HealthCheckAgent>();

    /// <summary>Gets or sets the attack command.</summary>
    /// <value>The attack command.</value>
    /// <autogeneratedoc />
    [StringLength(256)]
    public string AttackCmd { get; set; } = null!;

    /// <summary>Gets or sets the type of the check.</summary>
    /// <value>The type of the check.</value>
    /// <autogeneratedoc />
    public int CheckType { get; set; }

    /// <summary>Gets or sets the expected cracks.</summary>
    /// <value>The expected cracks.</value>
    /// <autogeneratedoc />
    public int ExpectedCracks { get; set; }


    /// <summary>Gets or sets the type of the hash.</summary>
    /// <value>The type of the hash.</value>
    public virtual HashType HashType { get; set; } = null!;

    /// <summary>Gets or sets the identifier.</summary>
    /// <value>The identifier.</value>
    /// <autogeneratedoc />
    public int Id { get; set; }

    /// <summary>Gets or sets the status.</summary>
    /// <value>The status.</value>
    /// <autogeneratedoc />
    public HealthCheckStatus Status { get; set; }

    /// <summary>Gets or sets the time.</summary>
    /// <value>The time.</value>
    /// <autogeneratedoc />
    public DateTime Time { get; set; }

    /// <summary>Gets or sets the test hashes.</summary>
    /// <value>The test hashes.</value>
    public List<string> TestHashes { get; set; } = new();

    /// <summary>Gets or sets the hash list alias.</summary>
    /// <value>The hash list alias.</value>
    public string HashListAlias { get; set; } = null!;
}
