namespace HashSlinger.Api.Models;

using System.Diagnostics.CodeAnalysis;
using Enums;

/// <summary>
///     Represents the results of a health check. Serves as a mapping table between the agent, the healthcheck,
///     and the results.
/// </summary>
/// <autogeneratedoc />
public record HealthCheckAgent
{
    /// <summary>Gets or sets the agent.</summary>
    /// <value>The agent.</value>
    /// <autogeneratedoc />
    public virtual Agent Agent { get; set; } = null!;


    /// <summary>Gets or sets the health check.</summary>
    /// <value>The health check.</value>
    /// <autogeneratedoc />
    public virtual HealthCheck HealthCheck { get; set; } = null!;


    /// <summary>Gets or sets the cracked.</summary>
    /// <value>The cracked.</value>
    /// <autogeneratedoc />
    public int? Cracked { get; set; }

    /// <summary>Gets or sets the ending keyspace position.</summary>
    /// <value>The end.</value>
    /// <autogeneratedoc />
    public ulong? End { get; set; }

    /// <summary>Gets or sets the errors.</summary>
    /// <value>The errors.</value>
    /// <autogeneratedoc />
    public List<string> Errors { get; set; } = new();


    /// <summary>Gets or sets the identifier.</summary>
    /// <value>The identifier.</value>
    /// <autogeneratedoc />
    public int Id { get; set; }

    /// <summary>Gets or sets the number GPUs.</summary>
    /// <value>The number GPUs.</value>
    /// <autogeneratedoc />
    [SuppressMessage("ReSharper", "IdentifierTypo")]
    public int? NumGpus { get; set; }

    /// <summary>Gets or sets the starting keyspace position.</summary>
    /// <value>The start.</value>
    /// <autogeneratedoc />
    public ulong? Start { get; set; }

    /// <summary>Gets or sets the status.</summary>
    /// <value>The status.</value>
    /// <autogeneratedoc />
    public HealthCheckStatus Status { get; set; }
}
