namespace HashSlinger.Api.Models;

using System.ComponentModel.DataAnnotations;

/// <summary>Represents an entry in the log.</summary>
/// <autogeneratedoc />
public record LogEntry
{
    /// <summary>Gets or sets the identifier.</summary>
    /// <value>The identifier.</value>
    /// <autogeneratedoc />
    public int Id { get; set; }

    /// <summary>Gets or sets the issuer.</summary>
    /// <value>The issuer.</value>
    /// <autogeneratedoc />
    [StringLength(50)]
    public string Issuer { get; set; } = null!;


    /// <summary>Gets or sets the issuer identifier.</summary>
    /// <value>The issuer identifier.</value>
    /// <autogeneratedoc />
    [StringLength(50)]
    public string IssuerId { get; set; } = null!;

    /// <summary>Gets or sets the level.</summary>
    /// <value>The level.</value>
    /// <autogeneratedoc />
    [StringLength(50)]
    public string Level { get; set; } = null!;

    /// <summary>Gets or sets the message.</summary>
    /// <value>The message.</value>
    /// <autogeneratedoc />
    public string Message { get; set; } = null!;

    /// <summary>Gets or sets the time.</summary>
    /// <value>The time.</value>
    /// <autogeneratedoc />
    public DateTime Time { get; set; }
}
