namespace HashSlingerApi.Models;

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

/// <summary>Represents a configured preprocessor tool.</summary>
/// <autogeneratedoc />
public class Preprocessor
{
    /// <summary>Gets or sets the identifier.</summary>
    /// <value>The identifier.</value>
    /// <autogeneratedoc />
    public int Id { get; set; }

    /// <summary>Gets or sets the name.</summary>
    /// <value>The name.</value>
    /// <autogeneratedoc />
    [StringLength(256)]
    public string Name { get; set; } = null!;

    /// <summary>Gets or sets the URL.</summary>
    /// <value>The URL.</value>
    /// <autogeneratedoc />
    [StringLength(512)]
    public string Url { get; set; } = null!;


    /// <summary>Gets or sets the name of the binary.</summary>
    /// <value>The name of the binary.</value>
    /// <autogeneratedoc />
    [StringLength(256)]
    public string BinaryName { get; set; } = null!;


    /// <summary>Gets or sets the keyspace command.</summary>
    /// <value>The keyspace command.</value>
    /// <autogeneratedoc />
    [StringLength(256)]
    public string? KeyspaceCommand { get; set; }


    /// <summary>Gets or sets the skip command.</summary>
    /// <value>The skip command.</value>
    /// <autogeneratedoc />
    [StringLength(256)]
    public string? SkipCommand { get; set; }


    /// <summary>Gets or sets the limit command.</summary>
    /// <value>The limit command.</value>
    /// <autogeneratedoc />
    [StringLength(256)]
    public string? LimitCommand { get; set; }
}
