namespace HashSlinger.Api.Models;

using System.ComponentModel.DataAnnotations;

/// <summary>A voucher code that allows a agent to automatically register.</summary>
/// <autogeneratedoc />
public record RegistrationVoucher
{
    private const string TokenChars = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789";
    private const int TokenLength = 10;
    private static readonly Random Random = new();

    /// <summary>Gets or sets the identifier.</summary>
    /// <value>The identifier.</value>
    /// <autogeneratedoc />
    public int Id { get; set; }


    /// <summary>
    ///     <para>Gets or sets the voucher code.</para>
    /// </summary>
    /// <value>The voucher.</value>
    /// <autogeneratedoc />
    [StringLength(100)]
    public string Voucher { get; set; } = null!;

    /// <summary>Gets or sets the expiration.</summary>
    /// <value>The time when the voucher is no longer value, if not used.</value>
    /// <autogeneratedoc />
    public DateTime Expiration { get; set; }

    /// <summary>Gets the random token.</summary>
    /// <returns>
    ///     <br />
    /// </returns>
    public string GetRandomToken()
    {
        return new string(Enumerable.Repeat(TokenChars, TokenLength)
            .Select(s => s[Random.Next(s.Length)])
            .ToArray());
    }
}
