namespace HashSlinger.Api.Models;

using System.ComponentModel.DataAnnotations;

/// <summary>An active user session.</summary>
/// <remarks>Not sure that tracking this makes much sense anymore.</remarks>
/// <autogeneratedoc />
public record Session
{
    /// <summary>Gets or sets the user.</summary>
    /// <value>The user.</value>
    /// <autogeneratedoc />
    public virtual User User { get; set; } = null!;

    /// <summary>Gets or sets the identifier.</summary>
    /// <value>The identifier.</value>
    /// <autogeneratedoc />
    public int Id { get; set; }

    /// <summary>Gets or sets a value indicating whether this instance is open.</summary>
    /// <value><c>true</c> if this instance is open; otherwise, <c>false</c>.</value>
    /// <autogeneratedoc />
    public bool IsOpen { get; set; }

    /// <summary>Gets or sets the last action date.</summary>
    /// <value>The last action date.</value>
    /// <autogeneratedoc />
    public DateTime LastActionDate { get; set; }

    /// <summary>Gets or sets the session key.</summary>
    /// <value>The session key.</value>
    /// <autogeneratedoc />
    [StringLength(256)]
    public string SessionKey { get; set; } = null!;

    /// <summary>Gets or sets the session lifetime, in seconds.</summary>
    /// <value>The session lifetime.</value>
    /// <autogeneratedoc />
    public int SessionLifetime { get; set; }

    /// <summary>Gets or sets the session start date.</summary>
    /// <value>The session start date.</value>
    /// <autogeneratedoc />
    public DateTime SessionStartDate { get; set; }

    /// <summary>Gets or sets the user identifier.</summary>
    /// <value>The user identifier.</value>
    /// <autogeneratedoc />
    public int UserId { get; set; }
}
