namespace HashSlinger.Api.Models;

/// <summary>A join table for mapping a preconfigured task to a supertask.</summary>
/// <autogeneratedoc />
public record SupertaskPretask
{
    /// <summary>Gets or sets the pretask.</summary>
    /// <value>The pretask.</value>
    /// <autogeneratedoc />
    public virtual PreconfiguredTask PreconfiguredTask { get; set; } = null!;

    /// <summary>Gets or sets the supertask.</summary>
    /// <value>The supertask.</value>
    /// <autogeneratedoc />
    public virtual Supertask Supertask { get; set; } = null!;

    /// <summary>Gets or sets the identifier.</summary>
    /// <value>The identifier.</value>
    /// <autogeneratedoc />
    public int Id { get; set; }

    /// <summary>Gets or sets the pretask identifier.</summary>
    /// <value>The pretask identifier.</value>
    /// <autogeneratedoc />
    public int PretaskId { get; set; }

    /// <summary>Gets or sets the supertask identifier.</summary>
    /// <value>The supertask identifier.</value>
    /// <autogeneratedoc />
    public int SupertaskId { get; set; }
}
