namespace HashSlinger.Api.Models;

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

/// <summary>Stores the output of a task.</summary>
/// <autogeneratedoc />
public class TaskDebugOutput
{
    /// <summary>Gets or sets the identifier.</summary>
    /// <value>The identifier.</value>
    /// <autogeneratedoc />
    public int Id { get; set; }

    /// <summary>Gets or sets the task identifier.</summary>
    /// <value>The task identifier.</value>
    /// <autogeneratedoc />
    public int TaskId { get; set; }

    /// <summary>Gets or sets the output.</summary>
    /// <value>The output.</value>
    /// <autogeneratedoc />
    [StringLength(256)]
    public string Output { get; set; } = null!;

    /// <summary>Gets or sets the task.</summary>
    /// <value>The task.</value>
    /// <autogeneratedoc />
    [ForeignKey("TaskId")]
    [InverseProperty("TaskDebugOutputs")]
    public virtual Task Task { get; set; } = null!;
}
