namespace HashSlinger.Shared.Models;

using System.ComponentModel.DataAnnotations;

/// <summary>An API key</summary>
/// <autogeneratedoc />
public record ApiKey
{
    /// <summary>Gets or sets the API group.</summary>
    /// <value>The API group.</value>
    /// <autogeneratedoc />
    public virtual ApiGroup ApiGroup { get; set; } = null!;

    /// <summary>Gets or sets the user.</summary>
    /// <value>The user.</value>
    /// <autogeneratedoc />
    public virtual User User { get; set; } = null!;

    /// <summary>Gets or sets the access count.</summary>
    /// <value>The access count.</value>
    /// <autogeneratedoc />
    public int AccessCount { get; set; }

    /// <summary>Gets or sets the access key.</summary>
    /// <value>The access key.</value>
    /// <autogeneratedoc />
    [StringLength(256)]
    public string AccessKey { get; set; } = null!;

    /// <summary>Gets or sets the API group identifier.</summary>
    /// <value>The API group identifier.</value>
    /// <autogeneratedoc />
    public int ApiGroupId { get; set; }

    /// <summary>Gets or sets the end date for when the key is valid.</summary>
    /// <value>The end date.</value>
    /// <autogeneratedoc />
    public DateTime EndValid { get; set; }

    /// <summary>Gets or sets the identifier.</summary>
    /// <value>The identifier.</value>
    /// <autogeneratedoc />
    public int Id { get; set; }

    /// <summary>Gets or sets the start date for when the key is valid.</summary>
    /// <value>The start date.</value>
    /// <autogeneratedoc />
    public DateTime StartValid { get; set; }

    /// <summary>Gets or sets the user identifier.</summary>
    /// <value>The user identifier.</value>
    /// <autogeneratedoc />
    public int UserId { get; set; }
}
