namespace HashSlinger.Shared.Models;

/// <summary>A chunk of a cracking task.</summary>
/// <autogeneratedoc />
public record Chunk
{
    /// <summary>Gets or sets the agent.</summary>
    /// <value>The agent.</value>
    /// <autogeneratedoc />
    public virtual Agent? Agent { get; set; }

    /// <summary>Gets or sets the hash binaries.</summary>
    /// <value>The hash binaries.</value>
    /// <autogeneratedoc />
    public virtual ICollection<BinaryHash> BinaryHashes { get; set; } = new List<BinaryHash>();

    /// <summary>Gets or sets the hashes.</summary>
    /// <value>The hashes.</value>
    /// <autogeneratedoc />
    public virtual ICollection<Hash> Hashes { get; set; } = new List<Hash>();

    /// <summary>Gets or sets the errors.</summary>
    /// <value>The errors.</value>
    public virtual ICollection<AgentError> Errors { get; set; } = new List<AgentError>();

    /// <summary>Gets or sets the task.</summary>
    /// <value>The task.</value>
    /// <autogeneratedoc />
    public virtual Task Task { get; set; } = null!;

    /// <summary>Gets or sets the agent identifier.</summary>
    /// <value>The agent identifier.</value>
    /// <autogeneratedoc />
    public int? AgentId { get; set; }

    /// <summary>Gets or sets the checkpoint.</summary>
    /// <value>The checkpoint.</value>
    /// <autogeneratedoc />
    public ulong Checkpoint { get; set; }

    /// <summary>Gets or sets the cracked.</summary>
    /// <value>The cracked.</value>
    /// <autogeneratedoc />
    public int Cracked { get; set; }

    /// <summary>Gets or sets the dispatch time.</summary>
    /// <value>The dispatch time.</value>
    /// <autogeneratedoc />
    public DateTime DispatchTime { get; set; }

    /// <summary>Gets or sets the identifier.</summary>
    /// <value>The identifier.</value>
    /// <autogeneratedoc />
    public int Id { get; set; }

    /// <summary>Gets or sets the length.</summary>
    /// <value>The length.</value>
    /// <autogeneratedoc />
    public ulong Length { get; set; }

    /// <summary>Gets or sets the progress.</summary>
    /// <value>The progress.</value>
    /// <autogeneratedoc />
    public int? Progress { get; set; }

    /// <summary>Gets or sets the skip.</summary>
    /// <value>The skip.</value>
    /// <autogeneratedoc />
    public ulong Skip { get; set; }

    /// <summary>Gets or sets the solve time.</summary>
    /// <value>The solve time.</value>
    /// <autogeneratedoc />
    public DateTime SolveTime { get; set; }

    /// <summary>Gets or sets the speed.</summary>
    /// <value>The speed.</value>
    /// <autogeneratedoc />
    public ulong Speed { get; set; }

    /// <summary>Gets or sets the state.</summary>
    /// <value>The state.</value>
    /// <autogeneratedoc />
    public int State { get; set; }

    /// <summary>Gets or sets the task identifier.</summary>
    /// <value>The task identifier.</value>
    /// <autogeneratedoc />
    public int TaskId { get; set; }
}
