namespace HashSlinger.Shared.Models;

/// <summary>A cracker binary. Typically hashcat.</summary>
/// <autogeneratedoc />
public record CrackerBinary : DownloadableBinary
{
    /// <summary>Gets or sets the type of the cracker binary.</summary>
    /// <value>The type of the cracker binary.</value>
    /// <autogeneratedoc />
    public virtual CrackerBinaryType CrackerBinaryType { get; set; } = null!;

    /// <summary>Gets or sets the health checks.</summary>
    /// <value>The health checks.</value>
    /// <autogeneratedoc />
    public virtual ICollection<HealthCheck> HealthChecks { get; set; } = new List<HealthCheck>();

    /// <summary>Gets or sets the tasks.</summary>
    /// <value>The tasks.</value>
    /// <autogeneratedoc />
    public virtual ICollection<Task> Tasks { get; set; } = new List<Task>();
}
