namespace HashSlinger.Shared.Models;

using System.ComponentModel.DataAnnotations;

/// <summary>A hash.</summary>
/// <autogeneratedoc />
public record Hash : HashBase
{
    /// <summary>Gets or sets the hash value.</summary>
    /// <value>The hash value.</value>
    /// <autogeneratedoc />
    public string HashValue { get; set; } = null!;


    /// <summary>Gets or sets the salt.</summary>
    /// <value>The salt.</value>
    /// <autogeneratedoc />
    [StringLength(256)]
    public string? Salt { get; set; }
}
