namespace HashSlinger.Shared.Models;

using System.ComponentModel.DataAnnotations;
using Mapster;

/// <summary>A voucher code that allows a agent to automatically register.</summary>
/// <autogeneratedoc />
public record RegistrationVoucher
{
    private const string TokenChars = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789";
    private const int TokenLength = 20;
    private static readonly Random Random = new();

    /// <summary>
    ///     <para>Gets or sets the access group.</para>
    /// </summary>
    [AdaptIgnore]
    public virtual AccessGroup? AccessGroup { get; set; }

    public virtual int? AccessGroupId { get; set; }

    /// <summary>Gets or sets the expiration.</summary>
    /// <value>The time when the voucher is no longer value, if not used.</value>
    /// <autogeneratedoc />
    public DateTime? Expiration { get; set; }

    /// <summary>Gets or sets the identifier.</summary>
    /// <value>The identifier.</value>
    /// <autogeneratedoc />
    public int Id { get; set; }


    /// <summary>
    ///     <para>Gets or sets the voucher code.</para>
    /// </summary>
    /// <value>The voucher.</value>
    /// <autogeneratedoc />
    [StringLength(100)]
    public string Voucher { get; set; } = null!;

    /// <summary>Gets the random token.</summary>
    /// <returns>
    ///     <br />
    /// </returns>
    public static string GetRandomToken()
    {
        return new string(Enumerable.Repeat(TokenChars, TokenLength).Select(s => s[Random.Next(s.Length)]).ToArray());
    }
}
