// <auto-generated />
using System;
using HashSlinger.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HashSlinger.Api.Migrations
{
    [DbContext(typeof(HashSlingerContext))]
    [Migration("20230529234241_AddedRegistrationVoucherToContext")]
    partial class AddedRegistrationVoucherToContext
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HashSlinger.Api.Models.AccessGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("AccessGroup");
                });

            modelBuilder.Entity("HashSlinger.Api.Models.AccessGroupAgent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessGroupId")
                        .HasColumnType("integer");

                    b.Property<int>("AgentId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AccessGroupId");

                    b.HasIndex("AgentId");

                    b.ToTable("AccessGroupAgent");
                });

            modelBuilder.Entity("HashSlinger.Api.Models.AccessGroupUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessGroupId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AccessGroupId");

                    b.HasIndex("UserId");

                    b.ToTable("AccessGroupUser");
                });

            modelBuilder.Entity("HashSlinger.Api.Models.Agent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClientSignature")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("CommandParameters")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("CpuOnly")
                        .HasColumnType("boolean");

                    b.Property<string>("Devices")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IgnoreErrors")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsTrusted")
                        .HasColumnType("boolean");

                    b.Property<string>("LastAct")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("LastIp")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("LastTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("OperatingSystem")
                        .HasColumnType("integer");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Uid")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Agent");
                });

            modelBuilder.Entity("HashSlinger.Api.Models.AgentError", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AgentId")
                        .HasColumnType("integer");

                    b.Property<int?>("ChunkId")
                        .HasColumnType("integer");

                    b.Property<string>("Error")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("TaskId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Time")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AgentId");

                    b.HasIndex("TaskId");

                    b.ToTable("AgentError");
                });

            modelBuilder.Entity("HashSlinger.Api.Models.AgentStat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AgentId")
                        .HasColumnType("integer");

                    b.Property<int>("StatType")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Time")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("AgentId");

                    b.ToTable("AgentStat");
                });

            modelBuilder.Entity("HashSlinger.Api.Models.AgentZap", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AgentId")
                        .HasColumnType("integer");

                    b.Property<int?>("LastZapId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AgentId");

                    b.HasIndex("LastZapId");

                    b.ToTable("AgentZap");
                });

            modelBuilder.Entity("HashSlinger.Api.Models.ApiGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Permissions")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ApiGroup");
                });

            modelBuilder.Entity("HashSlinger.Api.Models.ApiKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessCount")
                        .HasColumnType("integer");

                    b.Property<string>("AccessKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("ApiGroupId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("EndValid")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("StartValid")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ApiGroupId");

                    b.HasIndex("UserId");

                    b.ToTable("ApiKey");
                });

            modelBuilder.Entity("HashSlinger.Api.Models.Assignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AgentId")
                        .HasColumnType("integer");

                    b.Property<string>("Benchmark")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TaskId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AgentId");

                    b.HasIndex("TaskId");

                    b.ToTable("Assignment");
                });

            modelBuilder.Entity("HashSlinger.Api.Models.Chunk", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AgentId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Checkpoint")
                        .HasColumnType("numeric(20,0)");

                    b.Property<int>("Cracked")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DispatchTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Length")
                        .HasColumnType("numeric(20,0)");

                    b.Property<int?>("Progress")
                        .HasColumnType("integer");

                    b.Property<decimal>("Skip")
                        .HasColumnType("numeric(20,0)");

                    b.Property<DateTime>("SolveTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Speed")
                        .HasColumnType("numeric(20,0)");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.Property<int>("TaskId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AgentId");

                    b.HasIndex("TaskId");

                    b.ToTable("Chunk");
                });

            modelBuilder.Entity("HashSlinger.Api.Models.CrackerBinary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BinaryName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("CrackerBinaryTypeId")
                        .HasColumnType("integer");

                    b.Property<string>("DownloadUrl")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("CrackerBinaryTypeId");

                    b.ToTable("CrackerBinary");
                });

            modelBuilder.Entity("HashSlinger.Api.Models.CrackerBinaryType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsChunkingAvailable")
                        .HasColumnType("boolean");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.ToTable("CrackerBinaryType");
                });

            modelBuilder.Entity("HashSlinger.Api.Models.File", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessGroupId")
                        .HasColumnType("integer");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("FileType")
                        .HasColumnType("integer");

                    b.Property<bool>("IsSecret")
                        .HasColumnType("boolean");

                    b.Property<long?>("LineCount")
                        .HasColumnType("bigint");

                    b.Property<long>("Size")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("AccessGroupId");

                    b.ToTable("File");
                });

            modelBuilder.Entity("HashSlinger.Api.Models.FileDownload", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("FileId")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Time")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("FileId");

                    b.ToTable("FileDownload");
                });

            modelBuilder.Entity("HashSlinger.Api.Models.FilePretask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("FileId")
                        .HasColumnType("integer");

                    b.Property<int>("PretaskId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FileId");

                    b.HasIndex("PretaskId");

                    b.ToTable("FilePretask");
                });

            modelBuilder.Entity("HashSlinger.Api.Models.FileTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("FileId")
                        .HasColumnType("integer");

                    b.Property<int>("TaskId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FileId");

                    b.HasIndex("TaskId");

                    b.ToTable("FileTask");
                });

            modelBuilder.Entity("HashSlinger.Api.Models.Hash", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ChunkId")
                        .HasColumnType("integer");

                    b.Property<decimal>("CrackPos")
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("HashValue")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("HashlistId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsCracked")
                        .HasColumnType("boolean");

                    b.Property<string>("Plaintext")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Salt")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime?>("TimeCracked")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ChunkId");

                    b.HasIndex("HashlistId");

                    b.ToTable("Hash");
                });

            modelBuilder.Entity("HashSlinger.Api.Models.HashBinary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ChunkId")
                        .HasColumnType("integer");

                    b.Property<decimal>("CrackPos")
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("Essid")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("HashlistId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsCracked")
                        .HasColumnType("boolean");

                    b.Property<string>("Plaintext")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<DateTime?>("TimeCracked")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ChunkId");

                    b.HasIndex("HashlistId");

                    b.ToTable("HashBinary");
                });

            modelBuilder.Entity("HashSlinger.Api.Models.HashType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("IsSalted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSlowHash")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("HashType");
                });

            modelBuilder.Entity("HashSlinger.Api.Models.Hashlist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessGroupId")
                        .HasColumnType("integer");

                    b.Property<short>("BrainFeatures")
                        .HasColumnType("smallint");

                    b.Property<int>("BrainId")
                        .HasColumnType("integer");

                    b.Property<int>("Cracked")
                        .HasColumnType("integer");

                    b.Property<int>("Format")
                        .HasColumnType("integer");

                    b.Property<int>("HashCount")
                        .HasColumnType("integer");

                    b.Property<int>("HashTypeId")
                        .HasColumnType("integer");

                    b.Property<bool>("HexSalt")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSalted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSecret")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SaltSeparator")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.HasKey("Id");

                    b.HasIndex("AccessGroupId");

                    b.HasIndex("HashTypeId");

                    b.ToTable("Hashlist");
                });

            modelBuilder.Entity("HashSlinger.Api.Models.HashlistHashlist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("HashlistId")
                        .HasColumnType("integer");

                    b.Property<int>("ParentHashlistId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("HashlistId");

                    b.HasIndex("ParentHashlistId");

                    b.ToTable("HashlistHashlist");
                });

            modelBuilder.Entity("HashSlinger.Api.Models.HealthCheck", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AttackCmd")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("CheckType")
                        .HasColumnType("integer");

                    b.Property<int>("CrackerBinaryId")
                        .HasColumnType("integer");

                    b.Property<int>("ExpectedCracks")
                        .HasColumnType("integer");

                    b.Property<int>("HashtypeId")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Time")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CrackerBinaryId");

                    b.ToTable("HealthCheck");
                });

            modelBuilder.Entity("HashSlinger.Api.Models.HealthCheckAgent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AgentId")
                        .HasColumnType("integer");

                    b.Property<int>("Cracked")
                        .HasColumnType("integer");

                    b.Property<DateTime>("End")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Errors")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("HealthCheckId")
                        .HasColumnType("integer");

                    b.Property<int>("NumGpus")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Start")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AgentId");

                    b.HasIndex("HealthCheckId");

                    b.ToTable("HealthCheckAgent");
                });

            modelBuilder.Entity("HashSlinger.Api.Models.NotificationSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Notification")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("ObjectId")
                        .HasColumnType("integer");

                    b.Property<string>("Receiver")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("NotificationSetting");
                });

            modelBuilder.Entity("HashSlinger.Api.Models.Pretask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AttackCommand")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("ChunkTime")
                        .HasColumnType("integer");

                    b.Property<string>("Color")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("CrackerBinaryTypeId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsCpuTask")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsMaskImport")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSmall")
                        .HasColumnType("boolean");

                    b.Property<int>("MaxAgents")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<int>("StatusTimer")
                        .HasColumnType("integer");

                    b.Property<bool>("UseNewBench")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("CrackerBinaryTypeId");

                    b.ToTable("Pretask");
                });

            modelBuilder.Entity("HashSlinger.Api.Models.RegistrationVoucher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Expiration")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Voucher")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("RegistrationVouchers");
                });

            modelBuilder.Entity("HashSlinger.Api.Models.Session", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsOpen")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastActionDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SessionKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("SessionLifetime")
                        .HasColumnType("integer");

                    b.Property<DateTime>("SessionStartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Session");
                });

            modelBuilder.Entity("HashSlinger.Api.Models.Speed", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AgentId")
                        .HasColumnType("integer");

                    b.Property<decimal>("SpeedValue")
                        .HasColumnType("numeric(20,0)");

                    b.Property<int>("TaskId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Time")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AgentId");

                    b.HasIndex("TaskId");

                    b.ToTable("Speed");
                });

            modelBuilder.Entity("HashSlinger.Api.Models.Supertask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Supertask");
                });

            modelBuilder.Entity("HashSlinger.Api.Models.SupertaskPretask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("PretaskId")
                        .HasColumnType("integer");

                    b.Property<int>("SupertaskId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PretaskId");

                    b.HasIndex("SupertaskId");

                    b.ToTable("SupertaskPretask");
                });

            modelBuilder.Entity("HashSlinger.Api.Models.Task", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AttackCommand")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<decimal>("ChunkSize")
                        .HasColumnType("numeric(20,0)");

                    b.Property<int>("ChunkTime")
                        .HasColumnType("integer");

                    b.Property<string>("Color")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int?>("CrackerBinaryId")
                        .HasColumnType("integer");

                    b.Property<int?>("CrackerBinaryTypeId")
                        .HasColumnType("integer");

                    b.Property<bool>("ForcePipe")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsCpuTask")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSmall")
                        .HasColumnType("boolean");

                    b.Property<decimal>("Keyspace")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("KeyspaceProgress")
                        .HasColumnType("numeric(20,0)");

                    b.Property<int>("MaxAgents")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PreprocessorCommand")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<decimal>("SkipKeyspace")
                        .HasColumnType("numeric(20,0)");

                    b.Property<int>("StaticChunks")
                        .HasColumnType("integer");

                    b.Property<int>("StatusTimer")
                        .HasColumnType("integer");

                    b.Property<int>("TaskWrapperId")
                        .HasColumnType("integer");

                    b.Property<bool>("UseNewBenchmark")
                        .HasColumnType("boolean");

                    b.Property<bool>("UsePreprocessor")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("CrackerBinaryId");

                    b.HasIndex("CrackerBinaryTypeId");

                    b.HasIndex("TaskWrapperId");

                    b.ToTable("Task");
                });

            modelBuilder.Entity("HashSlinger.Api.Models.TaskDebugOutput", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Output")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("TaskId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TaskId");

                    b.ToTable("TaskDebugOutput");
                });

            modelBuilder.Entity("HashSlinger.Api.Models.TaskWrapper", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AccessGroupId")
                        .HasColumnType("integer");

                    b.Property<int>("Cracked")
                        .HasColumnType("integer");

                    b.Property<int>("HashlistId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<int>("TaskType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AccessGroupId");

                    b.HasIndex("HashlistId");

                    b.ToTable("TaskWrapper");
                });

            modelBuilder.Entity("HashSlinger.Api.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<bool>("IsValid")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastLoginDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<DateTime>("RegisteredSince")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("HashSlinger.Api.Models.Zap", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AgentId")
                        .HasColumnType("integer");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("HashlistId")
                        .HasColumnType("integer");

                    b.Property<long>("SolveTime")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("AgentId");

                    b.HasIndex("HashlistId");

                    b.ToTable("Zap");
                });

            modelBuilder.Entity("HashSlinger.Api.Models.AccessGroupAgent", b =>
                {
                    b.HasOne("HashSlinger.Api.Models.AccessGroup", "AccessGroup")
                        .WithMany("AccessGroupAgents")
                        .HasForeignKey("AccessGroupId")
                        .IsRequired();

                    b.HasOne("HashSlinger.Api.Models.Agent", "Agent")
                        .WithMany("AccessGroupAgents")
                        .HasForeignKey("AgentId")
                        .IsRequired();

                    b.Navigation("AccessGroup");

                    b.Navigation("Agent");
                });

            modelBuilder.Entity("HashSlinger.Api.Models.AccessGroupUser", b =>
                {
                    b.HasOne("HashSlinger.Api.Models.AccessGroup", "AccessGroup")
                        .WithMany("AccessGroupUsers")
                        .HasForeignKey("AccessGroupId")
                        .IsRequired();

                    b.HasOne("HashSlinger.Api.Models.User", "User")
                        .WithMany("AccessGroupUsers")
                        .HasForeignKey("UserId")
                        .IsRequired();

                    b.Navigation("AccessGroup");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HashSlinger.Api.Models.Agent", b =>
                {
                    b.HasOne("HashSlinger.Api.Models.User", "User")
                        .WithMany("Agents")
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HashSlinger.Api.Models.AgentError", b =>
                {
                    b.HasOne("HashSlinger.Api.Models.Agent", "Agent")
                        .WithMany("AgentErrors")
                        .HasForeignKey("AgentId")
                        .IsRequired();

                    b.HasOne("HashSlinger.Api.Models.Task", "Task")
                        .WithMany("AgentErrors")
                        .HasForeignKey("TaskId");

                    b.Navigation("Agent");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("HashSlinger.Api.Models.AgentStat", b =>
                {
                    b.HasOne("HashSlinger.Api.Models.Agent", "Agent")
                        .WithMany("AgentStats")
                        .HasForeignKey("AgentId")
                        .IsRequired();

                    b.Navigation("Agent");
                });

            modelBuilder.Entity("HashSlinger.Api.Models.AgentZap", b =>
                {
                    b.HasOne("HashSlinger.Api.Models.Agent", "Agent")
                        .WithMany("AgentZaps")
                        .HasForeignKey("AgentId")
                        .IsRequired();

                    b.HasOne("HashSlinger.Api.Models.Zap", "LastZap")
                        .WithMany("AgentZaps")
                        .HasForeignKey("LastZapId");

                    b.Navigation("Agent");

                    b.Navigation("LastZap");
                });

            modelBuilder.Entity("HashSlinger.Api.Models.ApiKey", b =>
                {
                    b.HasOne("HashSlinger.Api.Models.ApiGroup", "ApiGroup")
                        .WithMany("ApiKeys")
                        .HasForeignKey("ApiGroupId")
                        .IsRequired();

                    b.HasOne("HashSlinger.Api.Models.User", "User")
                        .WithMany("ApiKeys")
                        .HasForeignKey("UserId")
                        .IsRequired();

                    b.Navigation("ApiGroup");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HashSlinger.Api.Models.Assignment", b =>
                {
                    b.HasOne("HashSlinger.Api.Models.Agent", "Agent")
                        .WithMany("Assignments")
                        .HasForeignKey("AgentId")
                        .IsRequired();

                    b.HasOne("HashSlinger.Api.Models.Task", "Task")
                        .WithMany("Assignments")
                        .HasForeignKey("TaskId")
                        .IsRequired();

                    b.Navigation("Agent");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("HashSlinger.Api.Models.Chunk", b =>
                {
                    b.HasOne("HashSlinger.Api.Models.Agent", "Agent")
                        .WithMany("Chunks")
                        .HasForeignKey("AgentId");

                    b.HasOne("HashSlinger.Api.Models.Task", "Task")
                        .WithMany("Chunks")
                        .HasForeignKey("TaskId")
                        .IsRequired();

                    b.Navigation("Agent");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("HashSlinger.Api.Models.CrackerBinary", b =>
                {
                    b.HasOne("HashSlinger.Api.Models.CrackerBinaryType", "CrackerBinaryType")
                        .WithMany("CrackerBinaries")
                        .HasForeignKey("CrackerBinaryTypeId")
                        .IsRequired();

                    b.Navigation("CrackerBinaryType");
                });

            modelBuilder.Entity("HashSlinger.Api.Models.File", b =>
                {
                    b.HasOne("HashSlinger.Api.Models.AccessGroup", "AccessGroup")
                        .WithMany("Files")
                        .HasForeignKey("AccessGroupId")
                        .IsRequired();

                    b.Navigation("AccessGroup");
                });

            modelBuilder.Entity("HashSlinger.Api.Models.FileDownload", b =>
                {
                    b.HasOne("HashSlinger.Api.Models.File", "File")
                        .WithMany("FileDownloads")
                        .HasForeignKey("FileId")
                        .IsRequired();

                    b.Navigation("File");
                });

            modelBuilder.Entity("HashSlinger.Api.Models.FilePretask", b =>
                {
                    b.HasOne("HashSlinger.Api.Models.File", "File")
                        .WithMany("FilePretasks")
                        .HasForeignKey("FileId")
                        .IsRequired();

                    b.HasOne("HashSlinger.Api.Models.Pretask", "Pretask")
                        .WithMany("FilePretasks")
                        .HasForeignKey("PretaskId")
                        .IsRequired();

                    b.Navigation("File");

                    b.Navigation("Pretask");
                });

            modelBuilder.Entity("HashSlinger.Api.Models.FileTask", b =>
                {
                    b.HasOne("HashSlinger.Api.Models.File", "File")
                        .WithMany("FileTasks")
                        .HasForeignKey("FileId")
                        .IsRequired();

                    b.HasOne("HashSlinger.Api.Models.Task", "Task")
                        .WithMany("FileTasks")
                        .HasForeignKey("TaskId")
                        .IsRequired();

                    b.Navigation("File");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("HashSlinger.Api.Models.Hash", b =>
                {
                    b.HasOne("HashSlinger.Api.Models.Chunk", "Chunk")
                        .WithMany("Hashes")
                        .HasForeignKey("ChunkId");

                    b.HasOne("HashSlinger.Api.Models.Hashlist", "Hashlist")
                        .WithMany("Hashes")
                        .HasForeignKey("HashlistId")
                        .IsRequired();

                    b.Navigation("Chunk");

                    b.Navigation("Hashlist");
                });

            modelBuilder.Entity("HashSlinger.Api.Models.HashBinary", b =>
                {
                    b.HasOne("HashSlinger.Api.Models.Chunk", "Chunk")
                        .WithMany("HashBinaries")
                        .HasForeignKey("ChunkId");

                    b.HasOne("HashSlinger.Api.Models.Hashlist", "Hashlist")
                        .WithMany("HashBinaries")
                        .HasForeignKey("HashlistId")
                        .IsRequired();

                    b.Navigation("Chunk");

                    b.Navigation("Hashlist");
                });

            modelBuilder.Entity("HashSlinger.Api.Models.Hashlist", b =>
                {
                    b.HasOne("HashSlinger.Api.Models.AccessGroup", "AccessGroup")
                        .WithMany("Hashlists")
                        .HasForeignKey("AccessGroupId")
                        .IsRequired();

                    b.HasOne("HashSlinger.Api.Models.HashType", "HashType")
                        .WithMany("Hashlists")
                        .HasForeignKey("HashTypeId")
                        .IsRequired();

                    b.Navigation("AccessGroup");

                    b.Navigation("HashType");
                });

            modelBuilder.Entity("HashSlinger.Api.Models.HashlistHashlist", b =>
                {
                    b.HasOne("HashSlinger.Api.Models.Hashlist", "Hashlist")
                        .WithMany("HashlistHashlistHashlists")
                        .HasForeignKey("HashlistId")
                        .IsRequired();

                    b.HasOne("HashSlinger.Api.Models.Hashlist", "ParentHashlist")
                        .WithMany("HashlistHashlistParentHashlists")
                        .HasForeignKey("ParentHashlistId")
                        .IsRequired();

                    b.Navigation("Hashlist");

                    b.Navigation("ParentHashlist");
                });

            modelBuilder.Entity("HashSlinger.Api.Models.HealthCheck", b =>
                {
                    b.HasOne("HashSlinger.Api.Models.CrackerBinary", "CrackerBinary")
                        .WithMany("HealthChecks")
                        .HasForeignKey("CrackerBinaryId")
                        .IsRequired();

                    b.Navigation("CrackerBinary");
                });

            modelBuilder.Entity("HashSlinger.Api.Models.HealthCheckAgent", b =>
                {
                    b.HasOne("HashSlinger.Api.Models.Agent", "Agent")
                        .WithMany("HealthCheckAgents")
                        .HasForeignKey("AgentId")
                        .IsRequired();

                    b.HasOne("HashSlinger.Api.Models.HealthCheck", "HealthCheck")
                        .WithMany("HealthCheckAgents")
                        .HasForeignKey("HealthCheckId")
                        .IsRequired();

                    b.Navigation("Agent");

                    b.Navigation("HealthCheck");
                });

            modelBuilder.Entity("HashSlinger.Api.Models.NotificationSetting", b =>
                {
                    b.HasOne("HashSlinger.Api.Models.User", "User")
                        .WithMany("NotificationSettings")
                        .HasForeignKey("UserId")
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("HashSlinger.Api.Models.Pretask", b =>
                {
                    b.HasOne("HashSlinger.Api.Models.CrackerBinaryType", "CrackerBinaryType")
                        .WithMany("Pretasks")
                        .HasForeignKey("CrackerBinaryTypeId")
                        .IsRequired();

                    b.Navigation("CrackerBinaryType");
                });

            modelBuilder.Entity("HashSlinger.Api.Models.Session", b =>
                {
                    b.HasOne("HashSlinger.Api.Models.User", "User")
                        .WithMany("Sessions")
                        .HasForeignKey("UserId")
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("HashSlinger.Api.Models.Speed", b =>
                {
                    b.HasOne("HashSlinger.Api.Models.Agent", "Agent")
                        .WithMany("Speeds")
                        .HasForeignKey("AgentId")
                        .IsRequired();

                    b.HasOne("HashSlinger.Api.Models.Task", "Task")
                        .WithMany("Speeds")
                        .HasForeignKey("TaskId")
                        .IsRequired();

                    b.Navigation("Agent");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("HashSlinger.Api.Models.SupertaskPretask", b =>
                {
                    b.HasOne("HashSlinger.Api.Models.Pretask", "Pretask")
                        .WithMany("SupertaskPretasks")
                        .HasForeignKey("PretaskId")
                        .IsRequired();

                    b.HasOne("HashSlinger.Api.Models.Supertask", "Supertask")
                        .WithMany("SupertaskPretasks")
                        .HasForeignKey("SupertaskId")
                        .IsRequired();

                    b.Navigation("Pretask");

                    b.Navigation("Supertask");
                });

            modelBuilder.Entity("HashSlinger.Api.Models.Task", b =>
                {
                    b.HasOne("HashSlinger.Api.Models.CrackerBinary", "CrackerBinary")
                        .WithMany("Tasks")
                        .HasForeignKey("CrackerBinaryId");

                    b.HasOne("HashSlinger.Api.Models.CrackerBinaryType", "CrackerBinaryType")
                        .WithMany("Tasks")
                        .HasForeignKey("CrackerBinaryTypeId");

                    b.HasOne("HashSlinger.Api.Models.TaskWrapper", "TaskWrapper")
                        .WithMany("Tasks")
                        .HasForeignKey("TaskWrapperId")
                        .IsRequired();

                    b.Navigation("CrackerBinary");

                    b.Navigation("CrackerBinaryType");

                    b.Navigation("TaskWrapper");
                });

            modelBuilder.Entity("HashSlinger.Api.Models.TaskDebugOutput", b =>
                {
                    b.HasOne("HashSlinger.Api.Models.Task", "Task")
                        .WithMany("TaskDebugOutputs")
                        .HasForeignKey("TaskId")
                        .IsRequired();

                    b.Navigation("Task");
                });

            modelBuilder.Entity("HashSlinger.Api.Models.TaskWrapper", b =>
                {
                    b.HasOne("HashSlinger.Api.Models.AccessGroup", "AccessGroup")
                        .WithMany("TaskWrappers")
                        .HasForeignKey("AccessGroupId");

                    b.HasOne("HashSlinger.Api.Models.Hashlist", "Hashlist")
                        .WithMany("TaskWrappers")
                        .HasForeignKey("HashlistId")
                        .IsRequired();

                    b.Navigation("AccessGroup");

                    b.Navigation("Hashlist");
                });

            modelBuilder.Entity("HashSlinger.Api.Models.Zap", b =>
                {
                    b.HasOne("HashSlinger.Api.Models.Agent", "Agent")
                        .WithMany("Zaps")
                        .HasForeignKey("AgentId");

                    b.HasOne("HashSlinger.Api.Models.Hashlist", "Hashlist")
                        .WithMany("Zaps")
                        .HasForeignKey("HashlistId")
                        .IsRequired();

                    b.Navigation("Agent");

                    b.Navigation("Hashlist");
                });

            modelBuilder.Entity("HashSlinger.Api.Models.AccessGroup", b =>
                {
                    b.Navigation("AccessGroupAgents");

                    b.Navigation("AccessGroupUsers");

                    b.Navigation("Files");

                    b.Navigation("Hashlists");

                    b.Navigation("TaskWrappers");
                });

            modelBuilder.Entity("HashSlinger.Api.Models.Agent", b =>
                {
                    b.Navigation("AccessGroupAgents");

                    b.Navigation("AgentErrors");

                    b.Navigation("AgentStats");

                    b.Navigation("AgentZaps");

                    b.Navigation("Assignments");

                    b.Navigation("Chunks");

                    b.Navigation("HealthCheckAgents");

                    b.Navigation("Speeds");

                    b.Navigation("Zaps");
                });

            modelBuilder.Entity("HashSlinger.Api.Models.ApiGroup", b =>
                {
                    b.Navigation("ApiKeys");
                });

            modelBuilder.Entity("HashSlinger.Api.Models.Chunk", b =>
                {
                    b.Navigation("HashBinaries");

                    b.Navigation("Hashes");
                });

            modelBuilder.Entity("HashSlinger.Api.Models.CrackerBinary", b =>
                {
                    b.Navigation("HealthChecks");

                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("HashSlinger.Api.Models.CrackerBinaryType", b =>
                {
                    b.Navigation("CrackerBinaries");

                    b.Navigation("Pretasks");

                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("HashSlinger.Api.Models.File", b =>
                {
                    b.Navigation("FileDownloads");

                    b.Navigation("FilePretasks");

                    b.Navigation("FileTasks");
                });

            modelBuilder.Entity("HashSlinger.Api.Models.HashType", b =>
                {
                    b.Navigation("Hashlists");
                });

            modelBuilder.Entity("HashSlinger.Api.Models.Hashlist", b =>
                {
                    b.Navigation("HashBinaries");

                    b.Navigation("Hashes");

                    b.Navigation("HashlistHashlistHashlists");

                    b.Navigation("HashlistHashlistParentHashlists");

                    b.Navigation("TaskWrappers");

                    b.Navigation("Zaps");
                });

            modelBuilder.Entity("HashSlinger.Api.Models.HealthCheck", b =>
                {
                    b.Navigation("HealthCheckAgents");
                });

            modelBuilder.Entity("HashSlinger.Api.Models.Pretask", b =>
                {
                    b.Navigation("FilePretasks");

                    b.Navigation("SupertaskPretasks");
                });

            modelBuilder.Entity("HashSlinger.Api.Models.Supertask", b =>
                {
                    b.Navigation("SupertaskPretasks");
                });

            modelBuilder.Entity("HashSlinger.Api.Models.Task", b =>
                {
                    b.Navigation("AgentErrors");

                    b.Navigation("Assignments");

                    b.Navigation("Chunks");

                    b.Navigation("FileTasks");

                    b.Navigation("Speeds");

                    b.Navigation("TaskDebugOutputs");
                });

            modelBuilder.Entity("HashSlinger.Api.Models.TaskWrapper", b =>
                {
                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("HashSlinger.Api.Models.User", b =>
                {
                    b.Navigation("AccessGroupUsers");

                    b.Navigation("Agents");

                    b.Navigation("ApiKeys");

                    b.Navigation("NotificationSettings");

                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("HashSlinger.Api.Models.Zap", b =>
                {
                    b.Navigation("AgentZaps");
                });
#pragma warning restore 612, 618
        }
    }
}
